// DO NOT MODIFY THIS FILE.
// This entire file was automatically generated by ModAssemblyInfo.csproj.
// Make any needed changes in ModAssemblyInfo.csproj.

namespace ParkingPricing
{
    /// <summary>
    /// Make assembly info available as constant strings.
    /// </summary>
    public class ModAssemblyInfo
    {
        public const string Name        = "ParkingPricing";
        public const string Version     = "1.0.6";
        public const string Title       = "Parking Pricing";
        public const string Description = "Dynamically adjusts parking lot pricing throughout your city based on demand";
    }
}
